project:
  type: website
  output-dir: docs

website:
  title: "My first webseite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: Summer_School_Padova.qmd
        text: Summer_school_Padova

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



